"""One-shot initialiser — seeds `.brain/context.md` for a repo.

Walks the repo root, counts source-file extensions, detects stack marker
files (pyproject.toml / package.json / Cargo.toml / go.mod / pom.xml /
build.gradle), asks Qwen for a one-paragraph project overview, and writes
a pre-populated `.brain/context.md` that the user can edit. Idempotent:
existing `context.md` is not overwritten unless `force=True`.
"""

from __future__ import annotations

import datetime as dt
import os
from collections import Counter
from pathlib import Path

from .backend import BackendError, chat
from .brain_scanner import DEFAULT_EXCLUDE_DIRS, DEFAULT_SOURCE_EXTENSIONS

STACK_MARKERS: dict[str, tuple[str, ...]] = {
    "python": ("pyproject.toml", "setup.py", "requirements.txt"),
    "javascript": ("package.json",),
    "typescript": ("tsconfig.json",),
    "rust": ("Cargo.toml",),
    "go": ("go.mod",),
    "java": ("pom.xml", "build.gradle", "build.gradle.kts"),
}

TOP_EXTENSIONS_REPORTED = 5
TOP_DIRS_REPORTED = 8


def count_extensions(
    root: Path,
    extensions: frozenset[str] | None = None,
    exclude_dirs: frozenset[str] | None = None,
) -> Counter[str]:
    """Return a counter of source-file extensions under `root`."""
    ext_set = extensions if extensions is not None else DEFAULT_SOURCE_EXTENSIONS
    exclude_set = exclude_dirs if exclude_dirs is not None else DEFAULT_EXCLUDE_DIRS
    counter: Counter[str] = Counter()
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in exclude_set]
        for fname in filenames:
            suffix = Path(fname).suffix.lower()
            if suffix in ext_set:
                counter[suffix] += 1
    return counter


def detect_markers(root: Path) -> list[str]:
    """Return the names of stack marker files present directly under `root`."""
    found: list[str] = []
    for markers in STACK_MARKERS.values():
        for marker in markers:
            if (root / marker).exists():
                found.append(marker)
    return found


def infer_stacks(markers: list[str]) -> list[str]:
    """Map marker filenames back to stack labels. Preserves detection order."""
    stacks: list[str] = []
    for stack, marker_names in STACK_MARKERS.items():
        if any(m in markers for m in marker_names):
            stacks.append(stack)
    return stacks


def list_top_level_dirs(
    root: Path, exclude_dirs: frozenset[str] | None = None
) -> list[str]:
    """Return visible top-level directories under `root`, excluded ones filtered out."""
    exclude_set = exclude_dirs if exclude_dirs is not None else DEFAULT_EXCLUDE_DIRS
    try:
        entries = sorted(p.name for p in root.iterdir() if p.is_dir())
    except OSError:
        return []
    return [d for d in entries if d not in exclude_set and not d.startswith(".")]


async def _qwen_overview(
    project_name: str,
    stacks: list[str],
    markers: list[str],
    top_extensions: list[tuple[str, int]],
    top_dirs: list[str],
) -> str:
    ext_summary = ", ".join(f"{ext} ({n})" for ext, n in top_extensions) or "none"
    dir_summary = ", ".join(top_dirs) or "none"
    stack_summary = ", ".join(stacks) if stacks else "unknown"
    marker_summary = ", ".join(markers) if markers else "none"

    prompt = (
        "Describe this software project in 2-3 sentences based on the "
        "metadata below. Output only the paragraph, no preamble, no "
        "bullet lists.\n\n"
        f"- Project root folder: {project_name}\n"
        f"- Detected stack(s): {stack_summary}\n"
        f"- Marker files: {marker_summary}\n"
        f"- Top file extensions by count: {ext_summary}\n"
        f"- Top-level directories: {dir_summary}"
    )
    system = (
        "You write short, factual project overviews for later reference. "
        "Stick to what the metadata suggests. Do not speculate about "
        "features not implied by the file layout."
    )
    try:
        return (await chat(prompt, system=system)).strip()
    except BackendError:
        return (
            f"{project_name} — {stack_summary} project. Top file "
            f"extensions: {ext_summary}."
        )


def build_context_md(
    project_name: str,
    overview: str,
    stacks: list[str],
    markers: list[str],
    top_extensions: list[tuple[str, int]],
    total_source_files: int,
    generated_at: str,
) -> str:
    stack_line = ", ".join(stacks) if stacks else "_unknown_"
    marker_line = ", ".join(f"`{m}`" for m in markers) if markers else "_None._"
    ext_lines = "\n".join(f"- `{ext}` — {n} files" for ext, n in top_extensions)
    if not ext_lines:
        ext_lines = "_None._"
    return (
        f"# {project_name} — project context\n\n"
        f"_Generated by codebrain-init {generated_at}_\n\n"
        "## Overview\n\n"
        f"{overview}\n\n"
        "## Stack\n\n"
        f"- Detected: {stack_line}\n"
        f"- Marker files: {marker_line}\n"
        f"- Source files total: {total_source_files}\n\n"
        "## Top extensions\n\n"
        f"{ext_lines}\n\n"
        "## Notes for Claude\n\n"
        "<!-- Edit this section. Describe goals, invariants, conventions, "
        "things to avoid, or anything else Claude should know before "
        "touching this codebase. -->\n"
    )


async def init_repo(root: str, force: bool = False) -> str:
    """Create `.brain/context.md` for the repo rooted at `root`.

    Returns a human-readable status report ending with a recommended
    next-step command, or `[codebrain error] ...` on failure.
    """
    root_path = Path(root)
    if not root_path.exists():
        return f"[codebrain error] root not found: {root}"
    if not root_path.is_dir():
        return f"[codebrain error] root is not a directory: {root}"

    brain_dir = root_path / ".brain"
    context_path = brain_dir / "context.md"

    if context_path.exists() and not force:
        return (
            f"already initialized: {context_path} exists. "
            "Pass `force=True` to overwrite."
        )

    extension_counts = count_extensions(root_path)
    total_source_files = sum(extension_counts.values())
    top_extensions = extension_counts.most_common(TOP_EXTENSIONS_REPORTED)
    markers = detect_markers(root_path)
    stacks = infer_stacks(markers)
    top_dirs = list_top_level_dirs(root_path)[:TOP_DIRS_REPORTED]
    project_name = root_path.resolve().name

    overview = await _qwen_overview(
        project_name, stacks, markers, top_extensions, top_dirs
    )

    generated_at = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    content = build_context_md(
        project_name=project_name,
        overview=overview,
        stacks=stacks,
        markers=markers,
        top_extensions=top_extensions,
        total_source_files=total_source_files,
        generated_at=generated_at,
    )

    brain_dir.mkdir(exist_ok=True)
    context_path.write_text(content, encoding="utf-8")

    stack_report = ", ".join(stacks) if stacks else "unknown"
    ext_report = ", ".join(f"{ext} ({n})" for ext, n in top_extensions) or "none"
    return (
        f"Initialized `.brain/` for {project_name}.\n\n"
        f"Stack: {stack_report}\n"
        f"Top extensions: {ext_report}\n"
        f"Total source files: {total_source_files}\n\n"
        f"Written: {context_path}\n\n"
        f"Recommended next step:\n"
        f'  codebrain_scan_repo("{root_path}")'
    )
